# Site settings
title: MG
email: 
description: > # this means to ignore newlines until "baseurl:"
  Notes for myself. Ruby, Rails, Javascript, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 7ffqwe
github_username:  gmmt

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
